# Numpy

## Universal Array Functions

A universal function (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features. 

In [64]:
#For full documentation
website = "https://docs.scipy.org/doc/numpy/reference/ufuncs.html"
import webbrowser
webbrowser.open(website)

True

In [17]:
import numpy as np

In [47]:
# We create our array
arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
#Taking Square Roots
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [49]:
#Calcualting exponential (e^)
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [50]:
# Natural Logarithm
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [51]:
# Base 10 Log
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [52]:
# Get the minimum value
np.min(arr)

1

In [53]:
# Get the maximum value
np.max(arr)

10

### Binary Functions 
They require two arrays

In [54]:
#Random array (normal dist)
A = np.random.randn(10)
A

array([ 0.80645162,  0.04660941, -1.17816161,  1.93218572, -0.12581486,
        0.50251416, -1.552145  , -0.50763922, -0.47360651, -0.43086828])

In [55]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([ 1.61256029,  0.93343251,  0.07701415, -0.50187741,  0.47374206,
       -0.06089704,  0.67382722, -0.24357121, -1.52742062, -0.29453861])

#### Addition

In [56]:
#Addition
np.add(A,B)

array([ 2.41901191,  0.98004192, -1.10114745,  1.43030831,  0.3479272 ,
        0.44161712, -0.87831778, -0.75121043, -2.00102713, -0.72540689])

#### Subtraction

In [57]:
np.subtract(A,B)

array([-0.80610867, -0.8868231 , -1.25517576,  2.43406313, -0.59955692,
        0.5634112 , -2.22597221, -0.264068  ,  1.05381411, -0.13632967])

#### Division

In [58]:
np.divide(A, B)

array([  0.50010634,   0.04993335, -15.2979881 ,  -3.84991571,
        -0.26557672,  -8.25186522,  -2.30347626,   2.08415112,
         0.31006948,   1.46285841])

#### Maximun value

In [24]:
#Finding max or min between two arrays
print(A)
print(B)
np.maximum(A,B)

[ 0.36320424 -0.07681156  1.98989646 -0.42472296  1.15130731 -0.40462648
  1.03017021  0.30374943 -0.66134576 -0.30731543]
[-0.1524139   0.23711648 -0.65882543  0.41881076 -0.35060585 -0.81746477
  0.44467472 -1.32586805 -0.92681321  0.53594756]


array([ 0.36320424,  0.23711648,  1.98989646,  0.41881076,  1.15130731,
       -0.40462648,  1.03017021,  0.30374943, -0.66134576,  0.53594756])

In [33]:
# more simple example
np.maximum([10,20,25,40],[11,19,29,44])

array([11, 20, 29, 44])

#### Minimum value

In [36]:
a1 = np.array([10,20,25,40]) 
a2 = np.array([11,19,29,44])

np.minimum(a1, a2)

array([10, 19, 25, 40])

# Exercises!